### ISSUE TITLE
Cannot style button height, or font-size

### ISSUE THREAD

**Issue by mikehenrty** [gaia-components/gaia-button#1]
which would be helpful for when we have gaia-button inside gaia list. Right now, gaia-button is way too big for gaia-list.

**Comment by wilsonpage** [comment]
I think it would make more sense if we could style the height of the button
using normal CSS. Seems wrong to use a variable here. Button should also
just inherit the font-family.

**Comment by mikehenrty** [comment]
> I think it would make more sense if we could style the height of the button
> using normal CSS. Seems wrong to use a variable here. 

Good idea. I'll look into that.

> Button should also just inherit the font-family.

I don't agree. We have a default height, and a default min-width, so it makes sense that the font-family has default settings to look nice with these defaults.

**Comment by mikehenrty** [comment]
Fixed by #3.
